name: post-merge
description: Branch birleştirme sonrası otomatik işlemler
version: 1.0.0

triggers:
  - event: post-merge
    conditions:
      - type: branch_pattern
        pattern: "feature/*,bugfix/*,hotfix/*"

actions:
  - name: update_memory
    type: custom
    script: |
      from kairos.memory import ContextManager
      from kairos.agents import LinkAgent, GuardianAgent
      
      def update_project_memory():
          ctx = ContextManager()
          link = LinkAgent()
          guardian = GuardianAgent()
          
          # Merge değişikliklerini analiz et
          changes = ctx.analyze_merge_changes()
          
          # Bağlam tutarlılığını kontrol et
          if not guardian.verify_context_consistency(changes):
              return False
          
          # Bağlamı güncelle
          link.update_context(changes)
          
          # Bilgi grafını güncelle
          ctx.update_knowledge_graph(changes)
          
          # Vektör veritabanını güncelle
          ctx.update_vector_store(changes)
          
          return True

  - name: dependency_check
    type: security
    config:
      python:
        tool: safety
        level: high
      javascript:
        tool: npm audit
        level: high

  - name: integration_tests
    type: test
    config:
      python:
        tool: pytest
        markers: ["integration"]
      javascript:
        tool: jest
        testMatch: ["**/*.integration.test.js"]

  - name: update_docs
    type: documentation
    config:
      tools:
        - pdoc
        - typedoc
        - docusaurus
      outputs:
        api: docs/api
        site: docs/site

metrics:
  collect:
    - name: merge_success
      type: counter
      labels:
        source_branch: string
        target_branch: string
        result: [success, failure]

    - name: memory_updates
      type: counter
      labels:
        action: memory
        type: [context, graph, vector]
        result: [success, failure]

    - name: security_issues
      type: counter
      labels:
        type: [dependency, code]
        severity: [low, moderate, high, critical]

    - name: test_results
      type: counter
      labels:
        type: [unit, integration]
        result: [success, failure, skipped]

notifications:
  on_failure:
    - type: console
      format: detailed
    - type: slack
      channel: "#dev-alerts"
      format: summary
    - type: email
      to: ["team@kairos.dev"]
      format: detailed

  on_success:
    - type: console
      format: summary
    - type: slack
      channel: "#dev-updates"
      format: summary 