apiVersion: v1
kind: Service
metadata:
  name: kairos
  labels:
    app: kairos
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: kairos
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kairos
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.kairos.ai
    secretName: kairos-tls
  rules:
  - host: api.kairos.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kairos
            port:
              number: 80 