title: Kairos - The Context Keeper
description: An autonomous development supervisor leveraging context engineering
baseurl: "/kairos-context-keeper"
url: "https://turtir-ai.github.io"
plugins:
  - jekyll-redirect-from 