title: Kairos - The Context Keeper
description: An autonomous development supervisor leveraging context engineering
baseurl: "/kairos-context-keeper"
url: "https://turtir-ai.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 